FROM openjdk:8-jre-alpine

MAINTAINER delivery-engineering@netflix.com

RUN sed -i 's|http://dl-cdn.alpinelinux.org/alpine|https://mirrors.aliyun.com/alpine|g' /etc/apk/repositories


COPY ./kayenta-web/build/install/kayenta /opt/kayenta

RUN apk --no-cache add --update bash

RUN adduser -D -S spinnaker

USER spinnaker

CMD ["/opt/kayenta/bin/kayenta"]
